name: Bug Report
description: Report an issue that you're running into
labels: bug,needs-triage
body:
- type: checkboxes
  attributes:
    label: Checklist before submitting a bug report
    options:
    - label: "I've updated to the latest released version of the SDK"
      required: true
    - label: "I've searched for existing [Github issues](https://github.com/facebook/facebook-android-sdk/issues)"
      required: true
    - label: "I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)"
      required: true
    - label: "I've read the [Code of Conduct](CODE_OF_CONDUCT.md)"
      required: true
    - label: This issue is not security related and can safely be disclosed publicly on GitHub
      required: true
- type: input
  id: java-version
  attributes:
    label: Java version
    description: "Which Java version are you using when you find the bug?"
    placeholder: "X.X.X"
  validations:
    required: true
- type: input
  id: android-version
  attributes:
    label: Android version
    description: "Which Android version are you using when you find the bug?"
    placeholder: "Example: API 29, Android 11, ..."
  validations:
    required: true
- type: input
  id: sdk-version
  attributes:
    label: Android SDK version
    description: "Which Facebook Android SDK version are you using when you find the bug?"
    placeholder: "X.X.X"
  validations:
    required: true
- type: input
  id: install-platform-and-version
  attributes:
    label: Installation platform & version
    description: "Which install platform (package manager) are you using when you find the bug?"
    placeholder: "Maven, Gradle, Manual ... version X.X.X"
  validations:
    required: true
- type: dropdown
  id: package
  attributes:
    label: Package
    description: "In which package of Facebook Android SDK do you find the bug?"
    options:
      - Core & AppEvents
      - Login
      - Share
      - AppLinks
      - Messenger
      - Places
      - Gaming Services
      - Other / I don't know
  validations:
    required: true
- type: textarea
  id: goals
  attributes:
    label: Goals
    description: "What do you want to achieve?"
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected results
    description: "What do you expect to happen?"
  validations:
    required: true
- type: textarea
  id: actual
  attributes:
    label: Actual results
    description: "What actually happened? Can you provide a stack trace?"
  validations:
    required: true
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to reproduce
    description: "What are the steps necessary to reproduce the bug?"
- type: textarea
  id: code-samples
  attributes:
    label: Code samples & details
    description: "Please provide a code sample, as well as any additional details, to help us track down the issue. If you can provide a link to a test project that allows us to reproduce the issue, this helps us immensely in both the speed and quality of the fix.
    **Note:** Remember to format your code for readability.
    "
    value: "// INSERT YOUR CODE HERE"
    render: java
